### ISSUE TITLE
Introdução à engenharia de dados e exemplos práticos com pandas

### ISSUE THREAD

**Issue by gabriel-taufer** [grupy-sao-marcos/call4papers#1]
Meu objetivo é, de maneira leve, apresentar brevemente o que é e pra que serve a engenharia de dados, focando em um live coding com exemplos práticos de como usar o pandas pra analisar dados e outras possíveis aplicações. Mais detalhes disponíveis  nos slides.

[Link para a apresentação ](https://docs.google.com/presentation/d/1Hhjn8THjcoby98VBE3xMpdLpxo0oEzYcDBscJdGKJ2Q/edit?usp=sharing)

**Comment by Perceu** [comment]
Atividade aprovada para dia 16/03
